Repository abpio/abp-commercial-docs, pull requests merged in 2021-04, with the labels that each got.

#95 Fix order by
  en/tutorials/book-store/part-10.md
Labels: documentation

#94 Update Getting Started document
  en/getting-started-create-solution.md
  en/getting-started-running-solution.md
  en/images/suite-create-new-solution-Angular-Ef.png
Labels: documentation

#108 Add image compression Github action
  .github/workflows/image-compression.yml
Labels: enhancement

#117 Reviewing the microservice documents
  en/docs-nav.json
  en/images/apply-database-migrations.png
  en/startup-templates/microservice/applications.md
  en/startup-templates/microservice/database-migrations.md
  en/startup-templates/microservice/gateways.md
  en/startup-templates/microservice/get-started.md
  en/startup-templates/microservice/infrastructure.md
  en/startup-templates/microservice/microservices.md
  en/startup-templates/microservice/tye-integration.md
Labels: documentation, enhancement
